### ISSUE TITLE
options not working

### ISSUE THREAD

**Issue by Solence1** [phanx-wow/PhanxFont#1]
```
Message: Interface\AddOns\PhanxFont\Options.lua:56: Cannot find a library instance of "PhanxConfig-MediaDropdown".
Time: 02/19/18 17:14:46
Count: 1
Stack: Interface\AddOns\PhanxFont\Options.lua:56: Cannot find a library instance of "PhanxConfig-MediaDropdown".
[C]: ?
[C]: in function `error'
Interface\AddOns\PhanxFont\Libs\LibStub\LibStub.lua:23: in function `LibStub'
Interface\AddOns\PhanxFont\Options.lua:56: in function <Interface\AddOns\PhanxFont\Options.lua:39>
[C]: in function `Show'
Interface\FrameXML\InterfaceOptionsFrame.lua:28: in function `InterfaceOptionsList_DisplayPanel'
Interface\FrameXML\InterfaceOptionsFrame.lua:46: in function `InterfaceOptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals: 
```

**Comment by Solence1** [comment]
> 41x
> 
>  PhanxFont\Options-Options.lua:56: Cannot find a library instance of "PhanxConfig-MediaDropdown".
> [C]: in function `error'
> ...eAccountant_Classic\Libs\LibStub\LibStub.lua:38: in function `LibStub'
> PhanxFont\Options-Options.lua:56: in function <PhanxFont\Options.lua:39>
> [C]: in function `Show'
> FrameXML\InterfaceOptionsFrame.lua:28: in function `InterfaceOptionsList_DisplayPanel'
> FrameXML\InterfaceOptionsFrame.lua:46: in function `InterfaceOptionsListButton_OnClick'
> [string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>
> 
> Locals:
> (*temporary) = "Cannot find a library instance of "PhanxConfig-MediaDropdown"."
> 

this one i get when i have all addons enabled. thought maybe that can help.
i dont have accountant classic anymore

**Comment by scrable** [comment]
The TOC is pointing to the wrong location in file structure. 

Just change in PhanxFont.TOC
`Libs\PhanxConfig-Dropdown\PhanxConfig-Dropdown.lua`
`Libs\PhanxConfig-MediaDropdown\PhanxConfig-MediaDropdown.lua`
`Libs\PhanxConfig-Slider\PhanxConfig-Slider.lua`

to

`Config\Libs\PhanxConfig-Dropdown\PhanxConfig-Dropdown.lua`
`Config\Libs\PhanxConfig-MediaDropdown\PhanxConfig-MediaDropdown.lua`
`Config\Libs\PhanxConfig-Slider\PhanxConfig-Slider.lua`

**Comment by Phanx** [comment]
The TOC is actually correct; the embed paths for the packager script were wrong. Fixed and released.
