### ISSUE TITLE
Useability Issue

### ISSUE THREAD

**Issue by JDoubleU00** [phanx-wow/PhanxFont#2]
Maybe I am doing something wrong (i.e. PEBKC), but after installing this via Minion, I do not see the Lato font in drop down boxes.

Lines 20 and 21 in addon.lua the following code is present:

```
local NORMAL       = [[Interface\AddOns\PhanxMedia\font\Lato.ttf]]
local BOLD         = [[Interface\AddOns\PhanxMedia\font\Lato-Black.otf]]
```
I've even created a PhaxMedia folder with the font in it and no luck. 

One question on usability. If I pick a font and the scale in PhanxFont, do I need to manually adjust other addons?

**Comment by Phanx** [comment]
Already replied on WoWInterface, but to summarize for anyone who stumbles across this here:

1. You're not doing anything wrong. Those are just my personal default settings, and shouldn't have any effect on other users; you'll just default to the game default font (Friz Quadrata) and be able to choose from all the fonts registered with LibSharedMedia-3.0 by other addons. If you want to register your own fonts, see my [personal media script](https://github.com/phanx-wow/PhanxMedia) and read the instructions.

2. It depends on the addon. If the addon just inherits from a default game font (e.g. "GameFontNormal") then it will automatically follow whatever you do in PhanxFont. If the addon explicitly references a font file and/or size, then you'll have to manually adjust the addon's settings (or its code, if it doesn't have settings); there's no way for PhanxChat to know about fontstrings created/configured by other addons (without a hardcoded list of every addon and every fontstring it does/can create, which is obviously impossible). That said, I use 150+ addons (100+ of which weren't written by me) and if I change my font, I have to change settings in maybe 5 or 6 addons. Your experience may be different if you use a ton of addons that display a lot of text, but it probably won't be a huge effort.
